// Standalone magiskboot library
//
// Upstream: lib.rs defines CXX bridge. This standalone version replaces
// the CXX bridge with a Rust-native ffi module providing the same types.
//
// Wrapper approach: boot module .rs files are kept as close to upstream
// as possible. Differences are isolated in ffi.rs (shim) and compat
// re-exports below.

pub use base;
// Re-export argh module so #[derive(FromArgs)] macro can resolve argh::*
// The derive macro generates code like `argh::FromArgs`, `argh::parse_struct_args`, etc.
// This module wrapper makes those paths resolvable from any submodule.
pub mod argh {
    pub use base::argh::*;
}

pub mod ffi;

pub mod bootimg;
pub mod cli;
mod compat;
mod compress;
mod cpio;
mod dtb;
mod format;
mod patch;
mod payload;
// Suppress warnings in generated code
// Proto module is generated by build.rs into the proto/ directory
#[allow(warnings)]
#[path = "../proto/mod.rs"]
mod proto;
mod sign;

#[inline(always)]
pub(crate) fn check_env(env: &str) -> bool {
    std::env::var(env).is_ok_and(|var| var == "true")
}
