// Standalone magiskboot library — pure Rust, no C++ linkage.
//
// Upstream Magisk v30.7 kept the boot-image parser / unpack / repack
// in C++ and reached it from Rust through a CXX bridge. That shape
// aborted the host process when LTBox v3's GUI used the crate
// in-process on certain Lenovo ramdisks, so the boot-image
// pipeline was rewritten in Rust (see `bootimg/`).
//
// Wrapper approach: every other `boot/` submodule is kept as close
// to upstream as possible so future rebases stay cheap. The seam
// that used to span the Rust/C++ boundary now lives entirely in
// `ffi.rs` and `bootimg/`, plus the `compat` re-exports below.

pub use base;
// Re-export argh module so #[derive(FromArgs)] macro can resolve argh::*
// The derive macro generates code like `argh::FromArgs`, `argh::parse_struct_args`, etc.
// This module wrapper makes those paths resolvable from any submodule.
pub mod argh {
    pub use base::argh::*;
}

pub mod ffi;

pub mod bootimg;
pub mod cli;
mod compat;
mod compress;
mod cpio;
mod dtb;
mod format;
mod patch;
mod payload;
// Suppress warnings in generated code
// Proto module is generated by build.rs into the proto/ directory
#[allow(warnings)]
#[path = "../proto/mod.rs"]
mod proto;
mod sign;

#[inline(always)]
pub(crate) fn check_env(env: &str) -> bool {
    std::env::var(env).is_ok_and(|var| var == "true")
}
