// Stub for CXX-generated boot-rs.hpp
// In Magisk, this is auto-generated by cxx-build.
// For standalone build, we provide the signatures manually.
// Functions referenced by bootimg.cpp from Rust side are stubbed.

#pragma once

#include "base.hpp"

// These Rust functions are called from C++ via CXX bridge in upstream.
// For standalone build, we implement them in base.hpp or as stubs.
// compress_bytes, decompress_bytes, fmt2name, fmt_compressed,
// fmt_compressed_any, get_sha, sha256_hash, sign_payload —
// all already provided in base.hpp
